jdk:
  - openjdk17

before_install:
  - git submodule update --init --recursive
  - echo "Installing Android command-line tools..."
  - curl -sSLo /tmp/commandlinetools.zip "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"
  - unzip -q /tmp/commandlinetools.zip -d /tmp/cmdline-tools
  - mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
  - mv /tmp/cmdline-tools/cmdline-tools/* "$ANDROID_HOME/cmdline-tools/latest/" || true
  - rm -rf /tmp/commandlinetools.zip /tmp/cmdline-tools

  - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

  - echo "sdk.dir=$ANDROID_HOME" > platforms/android/local.properties
  - yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
  - ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-$ANDROID_API" "build-tools;$BUILD_TOOLS" "ndk;$NDK_VERSION" "cmake;$CMAKE_VERSION"

install:
  - bash -lc "cd platforms/android && ./gradlew tangram:assembleRelease tangram:publishAarPublicationToMavenLocal --stacktrace"

env:
  ANDROID_API: "36"
  NDK_VERSION: "28.2.13676358"
  BUILD_TOOLS: "35.0.0"
  CMAKE_VERSION: "3.30.5"