jdk:
  - openjdk17
before_install:
   - git submodule update --init
install:
  - bash -lc "cd platforms/android && ./gradlew tangram:assembleRelease tangram:publishAarPublicationToMavenLocal --stacktrace"